FROM docker.m.daocloud.io/debian:bookworm
ARG DEBIAN_FRONTEND=noninteractive

# replace the source list
RUN cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak && \
     sed -i 's|http://deb.debian.org/debian|http://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources && \
     sed -i 's|http://security.debian.org/debian-security|http://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources
RUN set -eux; cat /etc/apt/sources.list.d/debian.sources

RUN set -eux; apt-get update && apt-get upgrade --yes
RUN set -eux; apt-get install --yes curl gdb cmake build-essential git

# install gcovr 8.2.tar.gz
COPY 8.2.tar.gz /tmp/
RUN set -eux; apt-get update && apt-get upgrade --yes && apt-get install --yes python3-pip python3-venv samba-client
RUN set -eux; python3 -m venv /opt/venv && /opt/venv/bin/pip install --upgrade pip && /opt/venv/bin/pip install /tmp/8.2.tar.gz
RUN set -eux; /opt/venv/bin/pip install PyYAML

# install sccache
COPY sccache /usr/bin/sccache
RUN chmod +x /usr/bin/sccache
RUN sccache --version

# install gradlew to /root/gradle-8.10.2-bin/
ENV GRADLE_DIR="/root/gradle-8.10.2-bin/"
RUN mkdir -p "$GRADLE_DIR"
RUN curl -fL --retry 3 -C - \
  https://mirrors.cloud.tencent.com/gradle/gradle-8.10.2-bin.zip \
  -o "$GRADLE_DIR/gradle-8.10.2-bin.zip.part"
RUN set -eux; apt-get install --yes unzip
RUN unzip -q "$GRADLE_DIR/gradle-8.10.2-bin.zip.part" -d "$GRADLE_DIR" && \
  rm -f "$GRADLE_DIR/gradle-8.10.2-bin.zip.part"
ENV PATH="${GRADLE_DIR}/gradle-8.10.2/bin:${PATH}"

# install Andriod SDK
COPY scripts/install.sh /tmp/install.sh
RUN set -eux; chmod +x /tmp/install.sh && /tmp/install.sh

ENV ANDROID_HOME="/root/android-sdk" \
    ANDROID_SDK_ROOT="/root/android-sdk" \
    ANDROID_NDK_HOME="/root/android-sdk/ndk/24.0.8215888"

ENV PATH="/opt/venv/bin:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator:${ANDROID_NDK_HOME}:${PATH}"
